---
title: BA’s Best Coconut Cream Pie
date: 2025-10-07T10:29:04
draft: false
slug: bas-best-coconut-cream-pie
tags:
  - Pie
  - Custard
  - Coconut
  - Fruit
  - Graham Cracker
  - Baking
  - Easter
  - Vegetarian
categories:
  - Dessert
author: Claire Saffitz
servings: 10 servings
---

## Blurb

Think of this coconut cream pie recipe from pastry chef and former BA staffer Claire Saffitz as a Samoa cookie in pie form. It’s crunchy, caramelly, creamy, and positively jam-packed with coconut in all its many forms. You’ll find toasted coconut in the quick-and-dirty homemade pie crust, coconut oil in the caramel, coconut milk in the custard, and of course, flaked coconut to top it all off. (Catch Claire making the pie here.)This recipe takes time and is best approached in stages. Start with the graham cracker pie shell, which comes together with a quick blitz in a food processor, and gets a brief blind bake. Bundled in plastic wrap, it can be left out at room temperature for a day or frozen in the pie plate for up to two weeks. The coconut caramel, which adds that signature Samoa chew to the pie, can be made up to four days in advance.Save the creamy coconut filling for the day of serving—or one day before, max. Claire swaps out vanilla extract for a whole vanilla bean to really amp up the flavor, and uses half-and-half instead of whole milk for a richer mouthfeel. Once the pie filling’s poured into the crust, cover with plastic wrap (it should touch the custard!) so it doesn’t form a film and refrigerate.For the very last step, whipped cream goes perfectly with this coconut cream pie, but if you want to use up the extra egg whites, make a marshmallow topping. Bonus: You can torch it, for even more drama.For more custard pies, check out our recipes for Banana Cream Pie, Extremadura Almond Pie, Key Lime Pie, or Milk and Honey Pie.Think of this like a Samoa cookie in pie form. It’s perfect with whipped cream on top, but if you want to use up the extra egg whites, make a marshmallow topping. Bonus: You can torch it, for even more drama.

## Ingredients

- 1¼ cups unsweetened finely shredded coconut
- 4 ounces graham crackers (about 7), lightly crushed
- 2 tablespoons sugar
- ¼ teaspoon kosher salt
- ¼ cup (½ stick) unsalted butter, melted, cooled
- 1 large egg yolk
- ⅓ cup sugar, divided
- ¼ cup heavy cream
- 2 tablespoons virgin coconut oil, melted
- ½ teaspoon kosher salt
- 3 tablespoons virgin coconut oil, room temperature
- 1 vanilla bean, split lengthwise
- 1 13.5-ounce can unsweetened coconut milk, shaken
- 1 cup half-and-half
- 1 large egg
- 4 large egg yolks
- 3 tablespoons cornstarch
- ¼ teaspoon kosher salt
- ½ cup plus 2 tablespoons sugar
- 1½ cups heavy cream
- Toasted coconut flakes (for serving)
- A 9-inch deep pie dish; a candy thermometer

## Instructions

1. Preheat oven to 350°. Arrange coconut in a thin, even layer on a rimmed baking sheet and bake, stirring halfway through, until golden brown, 5–8 minutes; let cool. Set aside ½ cup toasted coconut for the coconut caramel.
2. Pulse graham crackers, sugar, salt, and remaining ¾ cup toasted coconut in a food processor until crackers are coarsely ground. With the motor running, stream in butter, followed by yolk. Do not overprocess; you should have fine crumbs that are the texture of wet sand.
3. Transfer mixture to pie dish and press firmly and evenly up sides and across the bottom. Place pan on a rimmed baking sheet and bake until crust is set and edges are brown, 12–18 minutes. Let cool.
4. Do Ahead: Crust can be baked 1 day ahead. Let cool, wrap in plastic, and store at room temperature, or freeze up to 2 weeks.
5. Sprinkle a thin, even layer of sugar into a small heavy saucepan. Cook, undisturbed, over medium heat until mostly melted, about 3 minutes. Sprinkle another layer of sugar over and cook, stirring to incorporate granular sugar into melted sugar with a heatproof spatula, until melted, another minute or so. Repeat until you’ve used all sugar. Continue to cook, swirling saucepan (do not stir), until caramel is dark amber, about 30 seconds longer. Remove from heat and carefully pour in cream, stirring to combine (caramel will sputter and seize up, but don’t worry).
6. Return saucepan to low heat and cook, stirring, until any hardened bits of caramel are dissolved. Stir in oil until mixture is smooth, then fold in salt and reserved ½ cup toasted coconut. Let caramel cool in pan, then scrape into cooled crust and use an offset spatula to spread in an even layer. Cover with plastic and chill.
7. Do Ahead: Caramel can be made 4 days ahead. Transfer to an airtight container and chill. Rewarm over low heat before pouring into pie crust.
8. Place oil in a medium bowl and set a fine-mesh sieve over top; set aside. Scrape vanilla seeds into a heavy medium saucepan. Add vanilla pod and coconut milk. Bring to a simmer over medium heat and cook, stirring occasionally, until coconut milk is reduced to about 1 cup, 10–15 minutes. Add half-and-half and bring to a gentle simmer.
9. Meanwhile, briskly whisk egg, yolks, cornstarch, salt, and ½ cup sugar in another medium bowl until pale and thick, about 1 minute. Whisking constantly, slowly pour about ½ cup hot milk mixture into egg mixture. Go back to whisking milk mixture in saucepan, then slowly pour tempered egg mixture into saucepan. Cook over medium heat, whisking constantly, until foam has subsided and custard holds the marks of the whisk, about 2 minutes.
10. Immediately scrape custard into sieve and use a spatula to press mixture into bowl with oil; pluck out vanilla pod. Whisk strained custard until oil is incorporated and mixture is glossy and smooth.
11. Set bowl inside another large bowl of ice water. Whisk occasionally until custard is cool, about 3 minutes. Scrape custard into chilled pie crust and smooth top. Press a piece of plastic directly onto surface of custard to prevent a skin from forming, and chill until set, at least 3 hours.
12. Using an electric mixer on medium-high speed, beat cream in a large bowl until soft peaks form. Whisk in remaining 2 tablespoons sugar.
13. Remove plastic from surface of pie and dollop cream over set custard. Top with coconut flakes.
14. Do Ahead: Pie can be filled with custard 1 day ahead. Wrap in plastic and chill. Top with whipped cream and toasted coconut just before serving.

## End-blurb

Editor’s note: This recipe was originally published in May 2017 as part of BA’s Best, a collection of our essential recipes. Head this way for more of our favorite cream pie recipes →

## Comments

- Yummmm. This pie was heavenly! I followed the recipe with no substitutions, and had no troubles with the caramel. Fairly experienced home baker, with no formal training. Like a lot if bon appetit recipes, you have to tap into your foundations knowledge (although Claire provides pretty clear instructions in this one). Tip for the caramel- try letting the heavy cream come up to room temp before adding it, it won't seize up the sugar as much and will blend in easier with less heat, which will keep the caramel from being overcooked and burnt tasting or hard. Like others noticed, the coconut flavor in the cream layer was mild, but I loved that because it let the salty, coconutty, caramel and crust shine. I think the light whipped cream was the right choice, as a heavy, sweet meringue would have been a lot. I'll find something else for those egg whites :)
- Are you able to convert your measurements and temperatures for australian measurements? This cake looks.awesome!
- My family loves this recipe, and I make it for my husband's birthday every year. It's delicious.
- I have had this recipe set aside for several years, but finally decided to make it for Thanksgiving. The results were perfect. The crust eats more like a semi-crunchy coconut cookie. You can pick up this piece of pie with your fingers and eat like a piece of pizza. I actually loved that. The caramel portion came out perfect. It was on the soft chewy side - I noticed that it blended into the crust and/or was moistened by the cream filling. Certainly if you overcook caramel, it will either turn to be like hard candy OR it will be burned. Love the light texture change and flavor addition there. *I added about 3 TBL of toasted unsweetened coconut flakes on top of the caramel layer. Turned out to be genius for extra flavor. I actually made two pies, one with whipped cream and one with toasted Italian Meringue. I loved them both.
- This pie is fantastic! Takes a while to put together and lots of steps, but worth every minute you’ll spend on not. The only problem is the caramel. Made as directed it isn’t enough and it gets so hard on the bottom of the pie, you can’t cut it. I recommend more caramel and more cream in that caramel, so it’s not so hard. I make one cup of sugar, melted in 1/4 cup of water. Cooked to a golden brown, then 1/2 cup of heavy cream, 2 tbsp of coconut oil, and the toasted coconut. Delicious, and cuttable! I don’t use all of that caramel in the pie. It’s too much. But it’s delicious on ice cream, or in any place you might like a coconutty caramel sauce.
- I love it! I made it yesterday in 8 cm tart rings because I want to send it to my friends for the New Year gift. The coconut flavor is subtle and it pairs beautifully with custard, caramel and the crust. I couldn't find Graham Crackers in my country so I used coconut biscuits instead and omit the sugar, because the biscuits are already sweet. It's a complicated recipe, but it sure does worth it. Thanks!
- Unusually for me I followed the recipe nearly exactly, changing only the vanilla bean for a whack of vanilla paste. This pie is FANTASTIC. One of the best pies I ever tasted - made it first time yesterday for dinner company and they hoovered it like wolves, all gone. I'm an experienced home cook but not trained, and had no issues with any of the steps. Mine is full of coconut flavour so not sure why any would find it bland. Well done, Claire; I'm sure I'll make this many times!
- Amazing. I added a layer of coconut chocolate ganache on top of the caramel (recipe from Epicurious).
- This is literally the best pie I've ever had. I made this for my family and they won't stop raving about it! The only change I made to the recipe is that I used brown butter for the pie crust, but I don't think it made much of a difference.
- This recipe is BOMB. And I would like to address some of the older comments about people failing at making the caramel. I had the same issues, and I tried 3 different times. The last time worked well all because I had a heavy bottom pot that held more heat and allowed the cream to incorporate into the caramel. It has to stay warm! Or it will turn to hard candy caramel and REALLY seize up!
- I never liked coconut cream pie until this recipe. I love coconut but felt most coconut cream pies were bland with little coconut flavor. I love how this recipe packs coconut into everything from the crust to the caramel to the filling. After reading the reviews, I did add a teaspoon of coconut extract to the filling which I thought was a welcome addition. Every time I’ve made it, I’ve found the coconut toasts fairly quickly (around 4 minutes). I initially burnt a few batches of coconut flakes. The crust was also on the lower end of the 12-18 for me - would just keep a close eye out. This is a fairly involved recipe and fairly time consuming. I think it’s best to make it a day ahead and keep in the fridge overnight. Best to give the filling plenty of time to set. I have made this recipe multiple times and will keep it as a standby!
- i love Claire's Coconut Cream Pie recipe so much, i pinned it twice! i'd add more coconut to both crust and custard, but i love the simple whipped cream topping. less sweet and more creamy than the meringue i thought she was going to make, what with all those egg whites just sitting around! Claire -- you are a baking genius! -- so much knowledge and experience; just a great teacher! (psst -- whenever there are leftover egg whites, ... MERINGUE COOKIES!)
- Yum! This was simply amazing! Everyone who ate it said it was the best coconut pie they've ever had. I personally don't like coconut cream pie, but I loved this. Just a couple things I would mention. First I would beat the egg yolk then stream it into the food processor. Next the caramel. Like the recipe says it will seize up, don't worry just keep stirring. I wouldn't serve this straight from the fridge or the caramel might be a bit chewy. Just set it out for an hour or so and it's wonderful.
- The pie was delish! My complain would be like most, the caramel layer. It was hard and super chewy. I would adjust that for sure. Other than that the pie was delicious. Flavor was there. Coconut-y but not overpowering.
- Oh Claire the things you do to me. I have made very few pies in my life. This pie was so good, even better the day after. Her caramel method didn’t work for me (which I came to accept after 2 tries) so I went with the wet caramel method and added 1/4 cup water to 1/3 cup sugar and let that caramelize which was perfect. All in all a crowd pleaser. Subtle coconut flavour but definitely there, and not too sweet. I did actually omit a bit of sugar from the custard which I could’ve eaten all of straight out of the bowl.
