---
title: BA's Best Baked Ziti
date: 2025-10-07T10:14:56
draft: false
slug: bas-best-baked-ziti
tags:
  - Pasta
  - Casserole
  - American
  - Mozzarella
  - Cheese
  - Canned Tomato
  - Tomato
  - Vegetable
  - Ziti
  - "Pasta & Noodles"
  - Main
  - "Nut-Free"
  - Dinner
categories:
  - recipes
cuisine: Italian American
author: Dawn Perry
servings: 6 Servings
prep_time: 35 minutes
total_time: 1 hour 10 minutes
---
## Blurb

When the mercury drops, we make baked pasta dishes on repeat for cozy Sunday suppers. If you're new to cooking these large-format classics, learning how to make baked ziti is a good place to start. It's simpler and more forgiving than lasagna but still delivers comforting bites full of mozzarella cheese-pulls and those much coveted crunchy corners. This baked ziti recipe is designed to stay saucy. While many call for ricotta cheese, it has a tendency to get dry and grainy when baked, so we've swapped it for a creamy Parmesan béchamel. And in place of meatballs, ground turkey, or Italian sausage, we prefer a bit of pancetta, which adds a salty and porky hit to homemade tomato sauce without distracting from the overall composition. Despite this recipe's name, ziti pasta isn't mandatory. Any short, tube shape (like rigatoni, paccheri, or penne pasta) will do. Just be sure to cook it in a large pot of salted water until it is shy of al dente, since it will continue to cook in the oven. Finally, don't skip out on broiling the whole baked ziti before serving, it's key to a perfectly browned top. Like many baked pasta recipes, this one is hearty enough that it needs little accompaniment at the table beyond a big green salad (try this one with an Italian seasoning-inspired dressing) or some fresh veggies, and perhaps some garlic bread. Refrigerate the leftovers and enjoy them all week long.

## Ingredients

- 2 tablespoons unsalted butter
- 2 tablespoons all-purpose flour
- 2.25 cups whole milk, slightly warmed
- 2.5 cups grated Parmesan, divided
- Kosher salt, freshly ground pepper
- 1/4 cup olive oil
- 1 ounce pancetta (Italian bacon), finely chopped
- 1 large onion, chopped
- 4 garlic cloves, chopped
- 1/2 teaspoon crushed red pepper flakes
- 2 tablespoons tomato paste
- 1 28-oz. can plus 1 14-oz. can whole peeled tomatoes
- 1/4 cup chopped fresh basil
- 1 pound ziti, penne, or rigatoni
- 1 pound fresh mozzarella, cut into 1/2" pieces

## Instructions

1. Heat butter in a medium saucepan over medium until foamy. Sprinkle flour over and cook, whisking constantly, 1 minute. Gradually whisk in warm milk. Bring mixture to a boil, reduce heat, and simmer, whisking often, until béchamel is thickened to about the consistency of heavy cream and no longer feels grainy when rubbed between your fingers, 8-10 minutes (thoroughly cooking the mixture ensures a creamy sauce and eliminates any raw flour flavor). Remove from heat and add 2 cups Parmesan, whisking until cheese is melted and sauce is smooth. Set aside.
2. Heat oil in a large saucepan over medium-high. Cook pancetta, stirring often, until golden brown, about 2 minutes. Add onion, garlic, and red pepper flakes; season with salt and pepper. Cook, stirring often, until onion is golden and soft, 8-10 minutes. Add tomato paste and cook, stirring, until slightly darkened, about 2 minutes.
3. Add whole peeled tomatoes, crushing with your hands as you go, and season with salt and pepper. Bring sauce to a simmer and cook, stirring often, until slightly reduced and flavors have melded, 20-25 minutes. Let cool slightly, then transfer to a blender; pulse until mostly smooth (or use an immersion blender and purée directly in pot). Stir in basil and season with salt and pepper.
4. Meanwhile, preheat oven to 350°. Cook pasta in a large pot of boiling salted water, stirring occasionally, until very al dente, about 5 minutes (the pasta will continue to cook in the oven); drain.
5. Transfer reserved béchamel to a large bowl; add pasta and mozzarella and toss to combine. Add all but 1 cup tomato sauce and gently fold mixture a few times, leaving streaks of béchamel.
6. Transfer pasta mixture to a 13x9" or other 3-quart baking dish, dollop with remaining tomato sauce, and scatter remaining Parmesan over pasta. Bake until mozzarella is melted and sauce is bubbling around the edges, 15-20 minutes.
7. Heat broiler. Broil until pasta and cheese are dark brown in spots, about 4 minutes. Let pasta sit 5 minutes before serving.

## End-blurb

Editor's note: This recipe was originally published in March 2015 as part of BA's Best, a collection of our essential recipes. For more of our favorite casserole recipes, head this way →

## Comments

- This is how I make it w/o making my own sauce. 2 tablespoons unsalted butter 2 tablespoons all-purpose flour 2.25 cups whole milk, slightly warmed 2.5 cups grated Parmesan, divided Kosher salt, freshly ground pepper 1/4 cup olive oil 1 large onion, chopped 4 garlic cloves, chopped 1/2 teaspoon crushed red pepper flakes 1 28 oz jar of your favorite sauce 1 pound ziti, penne, or rigatoni 1 pound fresh mozzarella, cut into 1/2" pieces Preparation Step 1 Preheat oven to 350°. Cook pasta in a large pot of boiling salted water, stirring occasionally, until very al dente, about 5 minutes (the pasta will continue to cook in the oven); drain. Step 2 Meanwhile, heat butter in a medium saucepan over medium until foamy. Sprinkle flour over and cook, whisking constantly, 1 minute. Gradually whisk in warm milk. Bring mixture to a boil, reduce heat, and simmer, whisking often, until béchamel is thickened to about the consistency of heavy cream and no longer feels grainy when rubbed between your fingers, 8-10 minutes (thoroughly cooking the mixture ensures a creamy sauce and eliminates any raw flour flavor). Remove from heat and add 2 cups Parmesan, whisking until cheese is melted and sauce is smooth. Set aside. Step 3 When pasta is done, heat oil in a large saucepan over medium-high. Add onion, garlic, and red pepper flakes; season with salt and pepper. Cook, stirring often, until onion is golden and soft, 8-10 minutes. Transfer to a large bowl; Step 4 Add pasta and mozzarella and toss to combine. Add all but 1/2 cup sauce, add béchamel. Gently fold mixture a few times, leaving streaks of béchamel. Step 5 Transfer pasta mixture to a 13x9" or other 3-quart baking dish, dollop with remaining tomato sauce, and scatter remaining Parmesan over pasta. Bake until mozzarella is melted and sauce is bubbling around the edges, 15-20 minutes. Step 6 Heat broiler. Broil until pasta and cheese are dark brown in spots, about 4 minutes. Let pasta sit 5 minutes before serving.
- This is always a hit. I use crushed tomatoes in order to skip the blending step.
- This ziti tastes pretty good but is too rich for an entree. I love cheese, probably eat too much cheese, so I doubt I have ever said the following words in my life, but this recipe has too much cheese. Taste is okay but its so rich I have trouble finishing a small bowl. If you are debating trying this recipe out, consider making a half portion so you don't have a full casserole tray to finish, or just par down the mozzarella and skip the extra time it takes to make the overly rich bechamel to opt for ricotta.
- THE BEST pasta al forno recipe out there. You will never miss the ricotta. I feel like I've made this enough I can whip it up quick on a weekday night. Some tips 1) if you skip pancetta, add some extra salt to the dish 2) I get away only using 1 28oz can of crushed tomatoes...maybe it's that extra can that makes it too "soupy." 3) Use low moisture mozz to avoid watery spots. I also bake the dish with a foil cover, then broil uncovered. No take-out ziti will beat this gem!!!
- This looked much like what my Mama used to cook for us... so I gave it a go. Excellent! The depth of the oven dish was not specified, so as I had already doubled the pancetta... it then became quadrupled - bcz half of the pasta missed the boat, sorry to say! I was also lazy with the Bechamel. made only half of the quantity (and used corn flour in it; to make it into a 'binding agent) and it turned out so good (still enough for 6-7)
- Delicious! Loved the way this turned out! All transparency, I SKIPPED steps 2 and 3 by using a jar of organic tomato sauce. Sacrilegious? Perhaps. Cutting out over an hour of cook time? Priceless!
- Great bones for a ziti recipe. The Midwesterner in me substituted ground beef for the pancetta, and it worked very well. One thing to note: if you're not an experienced cook, this recipe took 2 1/2 hours from start to plate.
- I have made this recipe numerous times and love it. i see a lot of reviews saying that it is very involved and takes a lot of time to make. I Think the first time it can seem that way but after making it so many times It comes together quickly. I actually make the marinara in this recipe by its self and jar it. My wife won't eat spaghettis unless I use this sauce. but really it is very simple, saute some stuff add the paste and tomatoes simmer blend add basil and the sauce is done. And bechamel is easy also make rue add cheese and done...
- This will be the 4/5 occasion I'll be making and absolutely love it!,completely delicious. There is quite a lot of preparation and cooking time but the end result is well worth it. Highly recommended
- My family loves this recipe! It's quite a lot of work but worth it. It is a little saucy, so I don't use all of the sauce. It's a hit!
- Like some other people this recipe turned out too saucy and cheesy. I never thought that too much sauce and cheese would be a problem but it was. Very heavy and it took such a long time to make, I'm upset I didn't like it.
- Doubled garlic, put all the parm in the bechamel (whoops!), so then added more on top. Crazy cheese and saucy! Shocking there was no ricotta! Love it!
- Good flavor but too saucy and cheesy for my taste. Would remake in my own way
- ZITI GOOD. MAKE AGAIN YES. THANK U.
- This baked ziti is soooo good. It's a little involved but it's a great Sunday project. The bechamel is an amazing addition that really takes this to the next level. It's a lot of food and I'm just one person so I usually freeze half. It reheats really nicely.


## Metadata (YAML)

```yaml
title: BA's Best Baked Ziti
date: 2025-10-07T10:14:56
draft: false
slug: bas-best-baked-ziti
tags:
  - Pasta
  - Casserole
  - American
  - Mozzarella
  - Cheese
  - Canned Tomato
  - Tomato
  - Vegetable
  - Ziti
  - "Pasta & Noodles"
  - Main
  - "Nut-Free"
  - Dinner
categories:
  - recipes
cuisine: Italian American
author: Dawn Perry
servings: 6 Servings
prep_time: 35 minutes
total_time: 1 hour 10 minutes
```
