---
title: "Crispy Sheet-Pan Meatballs With Salsa Verde"
date: 2025-10-07T10:19:15
draft: false
slug: crispy-sheet-pan-meatballs-with-salsa-verde
tags:
  - Meatball
  - Ground Beef
  - Beef
  - Meat
  - Easy
  - Weeknight Meals
  - Quick
  - Main
  - Starter
  - "Dairy-Free"
  - Roast
  - Dinner
  - Basically
categories:
  - recipes
author: Lauren Schaefer
servings: 4 servings
---
## Blurb

If the word “meatballs” brings to mind some kind of long, elaborate Sunday cooking project, then this recipe is here to change your mind. No shade to the classic Italian American version, but they just don’t need three kinds of meat, a tedious sear and braise, or even tomato sauce to be incredibly delicious. When you stick with one type of meat, give them quick, high-heat roast in the oven, and serve them with an herby salsa verde, few things are as cheap, versatile, and weeknight-friendly as a sheet pan full of meatballs. Think of this recipe as a template, and the possibilities are endless—mess around with different spices, types of meat, herbs and other add-ins, and you can easily make these once a week without getting bored. They’re great on top of grain bowls, in noodle-y soups, as an appetizer, or on their own alongside a green salad or some simply roasted veggies. And don't sleep on that salsa verde—it might just become your new favorite put-on-everything sauce.

## Ingredients

- 2 garlic cloves, divided
- 2 cups packed mixed herbs, such as parsley, cilantro, basil, and/or dill, divided
- 3 Tbsp. drained capers
- ¼ cup walnuts
- 1 large egg
- 1 Tbsp. paprika
- 2 tsp. kosher salt, plus more
- 3 Tbsp. plus ½ cup extra-virgin olive oil, divided
- 1 cup panko (Japanese breadcrumbs)
- 1 lb. ground beef (20% fat)
- 1 lemon
- Freshly ground black pepper

## Instructions

1. Place a rack in center of oven; preheat to 425°. Finely grate 1 garlic clove into a medium bowl. Finely grate 1 more garlic clove into a small bowl. (The medium bowl is for your meatball mixture, and the small bowl is for your salsa verde, in case this part seems silly.)
2. Finely chop 2 cups mixed herbs. As we mentioned in the ingredients list, you can use any combo of soft herbs like parsley, dill, basil, and/or cilantro, but if you've only got one that's cool, too—we just love how green and complex they taste when mixed together. Transfer half to same medium bowl, then transfer remaining herbs to same small bowl.
3. Finely chop 3 Tbsp. capers. Transfer 2 Tbsp. capers to medium bowl, then transfer remaining 1 Tbsp. capers to small bowl. Chop ¼ cup walnuts and add to same medium bowl. If you've never added nuts to meatballs, you're in for a real treat; they lend great texture and flavor to the finished dish.
4. Whisk in 1 egg, 1 Tbsp. paprika, 2 tsp. salt, and 1 Tbsp. oil to bowl with walnuts.
5. Using clean hands, mix 1 cup panko into egg mixture. Add 1 lb. ground beef and continue to mix gently with your hands until incorporated, but do not overmix. This part is key—if you work the mixture too much, the meat will become tough and springy, almost like sausage, so use a gentle hand. Also: At this point, you can pinch off a little piece of the meatball mixture, crisp it in a skillet, and give it a taste to make sure the seasoning is to your liking. This is your last chance to make any tweaks before they all get cooked!
6. Drizzle 2 Tbsp. oil on a rimmed baking sheet. Roll beef mixture into 1½" balls (about the size of golf balls). Arrange 1" apart on pan.
7. Bake meatballs, shaking pan halfway through, until crispy on all sides, about 10 minutes. One cool thing about using all beef (instead of a beef-pork-veal combo) is that it's totally fine if the meatballs are a little pink in the middle.
8. While meatballs are cooking, you can finish that salsa verde. This is one of our all-time favorite sauces, and is delicious spooned over just about any piece of meat, roasted veg, or bowl of leftovers you can think of. Which is all to say: Get ready to have a lot more salsa verde in your life from here on out. Finely grate lemon zest into bowl with herbs and garlic. Halve the lemon you just zested and squeeze juice into bowl, using your hand to catch any seeds. (You can use a citrus squeezer for this if you've got one.) Add remaining ½ cup oil and stir to combine. Season with salt and pepper, taste, and add more seasoning if necessary—it should be good and punchy.
9. Transfer meatballs to a platter, and serve with salsa verde alongside.

## End-blurb



## Comments

- I plan to add pine nuts, because I have them to my lamb meatballs along with cilantro, mint and possibly dill. They sound great.
- These turned out great, and were fast to make! Because of nut allergies, subbed pepitas for the walnuts. The bit of crunch were a welcome addition to the meatballs. We used the salsa on some other smoked meats, it seems to work with everything.
- Super delish. Made them with lamb and pepitas (pumpkin seeds) with cilantro, mint, parsley and dill....wow!
- Question - is this made with raw walnuts or roasted?
- I'm on a bit of a meatball kick after making Molly's Mojo Meatballs several times this summer (I definitely recommend those as well). These meatballs crispy, moist, and flavorful. I swap the capers for olives because it's what I have in the fridge usually. I've used different combinations of herbs every time and they are always great. Most recently I made them with parsley, basil, and dill, served with the salsa verde as well as harissa potatoes from the Ottolenghi Simple cookbook.
- These were super yummy especially with the salsa verde. Omitted the walnuts because of a nut allergy in the family. Seemed like a lot of work for something that is basically more of a heavy hor d'oeuvres than dinner, but it would be worth making for a party if you prepared them ahead of time.
- I've made these twice now during the pandemic and they're just awesome. Pair it with some fresh arugula and BOOM. Only suggested edit: 1tsp of salt rather than 2. Much more palatable. Also careful with the chopping. I will always remember this salsa verde because I lost just a little bit of my pointer finger while furiously chopping :)
- Made these yesterday with ground turkey and they did not disappoint! I also only cilantro and basil, and followed the rest of the recipe pretty close to exact (changes: added a little cumin and smoked paprika in addition to regular paprika, and a sprinkle of TJs umami seasoning). The salsa was actually so great and we had no leftovers. Served this with some basmati rice on the side and a whole bunch of roasted veg. Would try this again!
- Loved this. Easy and delicious. I'm making the dish again this weekend. The Salsa Verde could easily become a staple.
- Incredible. I know it’s sacrilege but I prefer these to the meatballs that I would make in my Italian Sunday sauce. The sauce compliments excellently but they work surprisingly well in a tomato sauce as well! Love the addition of the capers and walnuts — just make sure to finely chop both.
- Loved it! These were a hit with my family of meatball lovers. They were sceptic about the capers but came around after trying them.
- 1000% would make it again. The green herby sauce is NOT optional. The meatballs on their own are meh really but that Verde. I will make it again and again and again.
- I didn't have panko and subbed with oats instead, and it seemed to be fine. The sauce could use more lemon juice. I made these on the stovetop and it turned out okay!
- My sister made these a few weeks ago, and they were incredible. I couldn't stop eating them before dinner. We added a few spices but pretty much stuck to the recipe. I still think about how delicious they were. Even the smell on its own was amazing.
- Simply amazing. Dynamic flavors. Capers are now a pantry staple.


## Metadata (YAML)

```yaml
title: "Crispy Sheet-Pan Meatballs With Salsa Verde"
date: 2025-10-07T10:19:15
draft: false
slug: crispy-sheet-pan-meatballs-with-salsa-verde
tags:
  - Meatball
  - Ground Beef
  - Beef
  - Meat
  - Easy
  - Weeknight Meals
  - Quick
  - Main
  - Starter
  - "Dairy-Free"
  - Roast
  - Dinner
  - Basically
categories:
  - recipes
author: Lauren Schaefer
servings: 4 servings
```
