---
title: Olive Oil Cake
date: 2025-10-07T10:27:48
draft: false
slug: olive-oil-cake
tags:
  - Cake
  - Olive Oil
  - Sugar
  - Flour
  - Bake
  - Dessert
  - Amaretto
  - Vermouth
  - Lemon Zest
  - Lemon Juice
  - Vanilla Extract
  - Egg
categories:
  - recipes
author: Claire Saffitz
servings: 8 servings
cook_time: 40–50 minutes
---
## Blurb

Even die-hard butter devotees admit that olive oil makes exceptionally good cakes. EVOO is liquid at room temperature, so it lends superior moisture over time. In fact, olive oil cake only improves the longer it sits-this dairy-free version will keep on your counter for days (not that it'll last that long).

## Ingredients

- 1.25 cups plus 2 tablespoons extra-virgin olive oil; plus more for pan
- 1 cup plus 2 tablespoons sugar; plus more
- 2 cups cake flour
- 1/3 cup almond flour or meal or fine-grind cornmeal
- 2 teaspoons baking powder
- 1/2 teaspoon baking soda
- 1/2 teaspoon kosher salt
- 3 tablespoons amaretto, Grand Marnier, sweet vermouth, or other liqueur
- 1 tablespoon finely grated lemon zest
- 3 tablespoons fresh lemon juice
- 2 teaspoons vanilla extract
- 3 large eggs
- A 9"-diameter springform pan

## Instructions

1. Preheat oven to 400°. Drizzle bottom and sides of pan with oil and use your fingers to coat. Line bottom with a round of parchment paper and smooth to eliminate air bubbles; coat parchment with more oil. Generously sprinkle pan with sugar and tilt to coat in an even layer; tap out excess. Whisk cake flour, almond flour, baking powder, baking soda, and salt in a medium bowl to combine and eliminate any lumps. Stir together amaretto, lemon juice, and vanilla in a small bowl.
2. Using an electric mixer on high speed (use whisk attachment if working with a stand mixer), beat eggs, lemon zest, and 1 cup plus 2 Tbsp. sugar in a large bowl until mixture is very light, thick, pale, and falls off the whisk or beaters in a slowly dissolving ribbon, about 3 minutes if using a stand mixer and about 5 minutes if using a hand mixer. With mixer still on high speed, gradually stream in 1.25 cups oil and beat until incorporated and mixture is even thicker. Reduce mixer speed to low and add dry ingredients in 3 additions, alternating with amaretto mixture in 2 additions, beginning and ending with dry ingredients. Fold batter several times with a large rubber spatula, making sure to scrape the bottom and sides of bowl. Scrape batter into prepared pan, smooth top, and sprinkle with more sugar.
3. Place cake in oven and immediately reduce oven temperature to 350°. Bake until top is golden brown, center is firm to the touch, and a tester inserted into the center comes out clean, 40-50 minutes. Transfer pan to a wire rack and let cake cool in pan 15 minutes.
4. Poke holes all over top of cake with a toothpick or skewer and drizzle with remaining 2 Tbsp. oil; let it absorb. Run a thin knife around edges of cake and remove ring from pan. Slide cake onto rack and let cool completely. For the best flavor and texture, wrap cake in plastic and let sit at room temperature at least a day before serving.
5. Do Ahead: Cake can be baked 4 days ahead. Store tightly wrapped at room temperature.

## End-blurb



## Comments

- It turned out very well; moist, and very flavourful - tastes like olive oil. But, it did brown quite a bit, so next time I make it I would cover it half way through
- I used gluten free baking flour and it worked great! I used lemoncello as the liquor and added powdered sugar, cardamom, and lemon zest on top. It was delicious! Love how versatile this cake is, and it was on the easier side!
- I messed up this recipe at literally every step and it still came out good. I was in a rush to bake a quick snacking cake to have with my coffee this morning so I didn't read through the instructions. Ingredients are usually listed in order of use but they are not here, so pay attention to the instruction.I combined the sugar with the dry ingredients, cutting it back to 3/4C because I didn't want it super sweet. Then I realized I was going to be whipping my eggs and needed the sugar for that. Oops🤦‍♀️ I used the remaining 1/4c of sugar with the eggs. I added the lemon zest at the end because I didn't see I was supposed to put it in with the eggs.And finally I left the oven on 400F for half the baking time and then realized I was supposed to lower it to 350F. So the last 20 minutes were at 350. It is definitely a bit dark on the bottom but still quite tasty. I don't have a springform pan but was able to easily invert the cake out from a regular cake pan and flip it back rightside up onto the cooling rack.All that messing up and it is still tasty! Exactly what I was in the mood for. I'm going to make a fresh cranberry sauce to go with it later. Not adding the extra oil on top because I don't think it needs it. Next time I'll do all the steps right and cut the sugar back some.
- First time making a cake that sounded odd but I became an instant fan. I used fresh squeezed orange juice and zest, amaretto, Grand Marnier and cardamon. Delish!!!
- Do we have to replace the 3 tbsp of Grand Marnier with another liquid if we dont want to use any alcohol in the cake?Can't wait to try this!
- I used AP flower, cornmeal, 1 tablespoon less of sugar, and brandy, it is very good. The type of cake to enjoy with a cappuccino. I will try next time with orange peel and orange juice instead of lemon.
- Followed the recipe exactly, with excellent results! I overbaked a tad (43 minutes) but the inside is still super moist. My only suggestion would be to up the citrus a bunch, more like 2 tablespoons of lemon zest or adding orange zest in addition. It was really delicious, and the texture and height of the cake was amazing.
- Followed the recipe exactly. I used grand marnier and meyer lemons. The cake finished at exactly 40 minutes with a great crust and an incredibly moist and dense inside. Finished with confectioners sugar on top.
- Beautifully flavourful, moist cake. Needs to be covered in the oven after about 15 mins, as long cooking time can cause excessive browning, or even slight burning on top.
- Delicious cake! Used Grand Marnier, and cornmeal. I made two cakes at once the first time, and the batter was runny and both cakes sank in the middle (however the texture of the cake did not suffer... it was not more dense in the center. I think the fault lies in having to beat the eggs a little longer than 3 minutes)That being said, I've tried making the cake on its own the very next day because I am *obsessed* with perfecting this beautiful cake! Found the previous batch a little sweet so for 1 cake, used 1/2 cup sugar, beat the eggs double the recommended amount in my stand mixer, streamed the oil extra slowly with a squeeze bottle (almost drop by drop) and the batter was of a better consistency. And it did not sink! Yay! Added some lemon juice in the olive oil drizzle post bake and it makes a difference. So delicious. I also dusted with a generous layer of icing sugar and a rosemary garnish for a beautiful presentation. A must-try, not-too-sweet, refined dessert that will please a large group
- I was wondering where I could find nutrition facts? Delicious cake.
- Beautiful and delicious cake! Made with regular AP flour and turned out fine. Served with roasted plums which was a good combo!
- This cake was a big hit with my humans! I have digestion issues with butter, so I'm always happy to find delicious butter-less recipes. I used corn meal (allergic to almonds) and Cointreau. For the oil final drizzle, I mixed in a tablespoon of fresh lemon juice to amp up the citrus flavor. It worked *really* well. I'm going to make this again when the it's blood orange season - I think that will be delicious, too.
- SO GOOD!! It tastes like a pound cake, with a lighter texture and LOVELY crust. I was worried about doing everything perfect, getting every flavor right but as a very beginner baker, I can say it turned out good. It is a perfect cake to experiment with flavor too- I served it with raspberries and mint, sprinkled with powdered sugar- so so good.
- Just based on the smell in the house and other reviews, I know this cake is going to be delightful! The anticipation of waiting until tomorrow is almost too much!


## Metadata (YAML)

```yaml
title: Olive Oil Cake
date: 2025-10-07T10:27:48
draft: false
slug: olive-oil-cake
tags:
  - Cake
  - Olive Oil
  - Sugar
  - Flour
  - Bake
  - Dessert
  - Amaretto
  - Vermouth
  - Lemon Zest
  - Lemon Juice
  - Vanilla Extract
  - Egg
categories:
  - recipes
author: Claire Saffitz
servings: 8 servings
cook_time: 40-50 minutes
```
