---
title: "One-Skillet Chicken with Buttery Orzo"
date: 2025-10-07T10:17:36
draft: false
slug: one-skillet-chicken-with-buttery-orzo
tags:
  - Dinner
  - Weeknight
  - Chicken Recipes
  - Fennel
  - Leek
  - Orzo
  - White Wine
  - Chicken Broth
  - Lemon Juice
  - Lemon Zest
  - Cast iron
categories:
  - recipes
author: Claire Saffitz
servings: 4 servings
cook_time: "35-47 minutes"
---
## Blurb

Why use a bunch of pots and pans when fennel, orzo, and chicken can be cooked in one?

## Ingredients

- Kosher salt, freshly ground pepper
- 6 skin-on, bone-in chicken thighs (about 2 pounds total), patted dry
- 3 tablespoons unsalted butter, divided
- 1 fennel bulb, chopped, plus fronds, chopped
- 1 leek, white and pale green parts only, chopped
- 8 ounces orzo
- 1/3 cup dry white wine
- 2.5 cups low-sodium chicken broth, divided
- 1 tablespoon fresh lemon juice
- 1 teaspoon finely grated lemon zest

## Instructions

1. Preheat oven to 400°. Rain salt and then some pepper all over chicken. Heat 2 Tbsp. butter in a medium cast-iron skillet over medium-high. Nestle chicken, skin side down, in skillet in a single layer with no gaps (if you can't quite fit them all, wait until chicken shrinks slightly, then puzzle in the remaining pieces). Cook until meat is opaque around the edges and skin is deep golden brown, 6-8 minutes. Turn chicken skin side up and transfer skillet to oven; bake, uncovered, until chicken is cooked through, 10-15 minutes. Transfer chicken to a plate.
2. Set same skillet over medium; combine fennel bulb and leek in skillet and sprinkle in some salt and pepper. Cook, tossing occasionally, until leek is looking golden around the edges, about 5 minutes. Add orzo and cook until pasta is darkened (it will take on a brown hue) to a nice nutty brown in spots and toasty smelling, about 3 minutes. Pour in wine and cook, stirring, until liquid is evaporated, about 1 minute. Add broth 1/2 cup at a time, stirring constantly and letting broth absorb before adding more, until orzo is tender and broth is mostly absorbed but pan is not dry, 10-15 minutes.
3. Remove skillet from heat, Taste and add more salt and pepper to your liking; mix in lemon juice and remaining 1 Tbsp. butter, then chopped fennel fronds. Pile chicken on top and finish with lemon zest.

## End-blurb



## Comments

- I've made this recipe twice now. It has become one of my favorites. I always have chicken thighs in the freezer and orzo in the pantry. And I'm happy to pick up veg on a walk in the morning. This one is a keeper in my book!
- delicious crowd pleaser - made this for the second time tonight, and while i still haven't followed the recipe exactly (never seem to have fennel or leeks on hand...), this recipe deserves all the praise for the risotto-style orzo prep. like other commenters, i do recommend some extra seasoning on the chicken/throughout and can see how this easily gets 'too buttery'. first time i made it i subbed half the butter for olive oil and it was great, this time i went full butter and the orzo was phenom.
- So Delicious! Added garlic and seasoned the chicken with italian seasoning as well. Substituted wine for apple cider vinegar as I'm not 21 yet so I couldn't make that purchase but it was still great! Also used regular chicken broth instead of low sodium and just lessened the overall salt that gets added per taste because I just find low sodium chicken broth doesn't have as much flavor. Overall great, family loved it and would definitely make again!
- I loved it! But I want to know: is the nutritional information of 800ish calories for all 4 servings? It seems a lot for one serving, but I don't know how it works on BA. Not all the recipes have nutritional info! Please let me know (:
- This is probably he best one-pot recipe I have ever made. The orzo cooked perfectly and the flavors were well-balanced. It's definitely too rich for everyday but I will for sure be making again.
- I give the recipe four stars but I give the dish I made 5. I made a few changes: -Whole wheat orzo -Only 2 tbs butter at the beginning, did not add any at the end -I added shallots and garlic to the leeks and fennel saute -I seasoned the chicken thighs lol. With Italian seasoning, black garlic pepper, and salt Ended up with perfection.
- Another amazing recipe! I didn't have fennel so used celery. I also used less butter. I did end up using the amoutn of broth mentioned in the recipe (other reviews mentioned to decrease the amount) but the orzo remained quite hard, so I kept adding more. The method of making the chicken skin crispy is phenomenal!
- Should have read more of the comments and cut back on the butter. Would like to try a 'lighter' version of this in the future. My husband took the 'rain salt' part literally and I felt that between the intitial seasoning and the chicken stock, it was just too too much. Also, I'd have increased the lemon juice and decreased the stock as a flavor profile. This holds the possibility of bringing out more of the fennel and leek flavors and lowering the salty creamy? I also like the idea of olive oil for half the butter. As for the chicken, we are fortunate to have a warming drawer and used that to keep it warm while cooking part two: leeks, fennel and orzo. And this is also where my biggest criticism lies: For a one pot meal - it required a lot of standing over the pot. So this is not necessarily something I'd serve for company, nor did it allow me to enjoy my salad. This truly has to be your ONLY pot meal of the night. That, the salt, and the fatty feel from all the butter and stock are the reasons it only gets 4 stars and not 5. But the promise of fennel and leek will certainly encourage me to try again.
- This was very yummy! I followed some advice from other reviewers and added a little bit of garlic, subbed bok choy for fennel, and used probably half a cup less of broth. If I were to make it again, I would let the skin crisp up more than the recipe says. This was my first time cooking orzo, and it was delicious!
- So good! My family doesn't like the taste of fennel so I subbed bok choy and it was perfect! I think some of the times were a little low-balled since my chicken and orzo both took more time than it said, but it was so worth it. I'll definitely make this again!!
- cooking orzo as if it was risotto is a DREAM... just the orzo with whatever you want on top is an absolute winner! :) (i won't rate it because i just followed the orzo part, but i would give it 10/10)
- Hi BA & Brad Leone, This is a stunning meal, I made a few tweaks just out of necessity, and I'll definitely cook this again. Tweaks; - swapped the orzo for par cooked lentils, freekeh & beans (soup mix) - lightly charred some broccoli with the chicken just to get some super greens! Yeah super greens! - used ghee instead of butter for the first stage My wife and I loved this dinner. Sending cheers from Rye, Victoria, Australia. Pesty
- This recipe is a WINNER! So easy, so delicious, and hardly any clean up necessary. I have a feeling that I'll be making this again and again.
- Amazing! Family favorite and so ridiculously easy!
- How do you keep the chicken warm if there is still about 20 minutes of cooking after the chicken comes out of the oven?


## Metadata (YAML)

```yaml
title: "One-Skillet Chicken with Buttery Orzo"
date: 2025-10-07T10:17:36
draft: false
slug: one-skillet-chicken-with-buttery-orzo
tags:
  - Dinner
  - Weeknight
  - Chicken Recipes
  - Fennel
  - Leek
  - Orzo
  - White Wine
  - Chicken Broth
  - Lemon Juice
  - Lemon Zest
  - Cast iron
categories:
  - recipes
author: Claire Saffitz
servings: 4 servings
cook_time: "35-47 minutes"
```
